### ISSUE TITLE
App crashes in the background with `The calling thread must be STA`

### ISSUE THREAD

**Issue by vhatsura** [ShankarBUS/ModernFlyouts#105]
```
Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.InputManager.get_Current()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at ModernFlyouts.SettingsWindow..ctor()
   at ModernFlyouts.FlyoutHandler.ShowSettingsWindow()
   at ModernFlyouts.Program.RunCommand(CommandType commandType)
   at ModernFlyouts.Program.ProcessCommandLineArgs(IList`1 args, Boolean isFirstInstance)
   at ModernFlyouts.Program.CreateRemoteService(String channelName)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
```
Faulting application name: ModernFlyouts.exe, version: 0.6.8.0, time stamp: 0x5f4ed7fa
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x42f14898
Exception code: 0xe0434352
Fault offset: 0x00129962
Faulting process id: 0x4c98
Faulting application start time: 0x01d6a12377ac641a
Faulting application path: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.6.8.0_x86__pcy8vm99wrpcg\ModernFlyouts\ModernFlyouts.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 79313b1b-9b3e-46ef-a5a2-09c751e38f6f
Faulting package full name: 32669SamG.ModernFlyouts_0.6.8.0_x86__pcy8vm99wrpcg
Faulting package-relative application ID: App
```

**Comment by ShankarBUS** [comment]
Thanks for the report 😄.

 I'll look into this.

**Comment by ShankarBUS** [comment]
@vhatsura, Thanks for reporting this bug.

This is indeed a serious issue. Found the cause and fixed it in 1063dd4f27318ec0b913a5340ee86b19182b1e71

**Comment by ShankarBUS** [comment]
Hey @Samuel12321, don't forget to include this in v0.7

**Comment by Samuel12321** [comment]
😉 will do
